### ISSUE TITLE
Long delay when muting and unmuting

### ISSUE THREAD

**Issue by ktelep** [dakota-mewt/mewt#1]
Discord invite in README appears expired.  

I'm seeing up to a 5 second delay between hitting the button and the mute or unmute occurring.  Is there a way to reduce this delay?

**Comment by dakota-mewt** [comment]
Hi Kurt,

Thanks for letting me know.

Can you try this discord invite instead?  I'll update on github and hope to
see you on discord soon to troubleshoot.

https://discord.gg/FMm7zVdPhs

**Comment by dakota-mewt** [comment]
my response time is typically from 200 - 500ms (1/5 to 1/2 a second).  5
second isn't normal.

**Comment by dakota-mewt** [comment]
spoke with @ktelep.  the latency is unrelated to Mewt.  500ms (0.5 second) reaction time when tested on different PC.  Fresh reboot on problem PC brought time down to 1.5 seconds.
