### ISSUE TITLE
Does not work OOTB

### ISSUE THREAD

**Issue by LeeFried** [dakota-mewt/mewt#4]
I've spent an hour fixing bugs in the compiling of the Windows .ino file. I'm still not done. This is total bullshit. Can't believe I wasted my time with this. Repurposing this Arduino UNO for CANBUS acquisition.

**Comment by dakota-mewt** [comment]
Firstly, I'm sorry you are having issues.  Please feel free to join the Discord channel and I'm happy to work through it with you.  The ino file(s) have worked for a bunch of people, it'd be interesting to see what is happening here.

Second, that is very harsh and unnecessary language.  I'd suggest considering some civility.
